# Generated by Django 5.0.6 on 2024-08-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentform',
            new_name='Student',
        ),
    ]
